.\"	$NetBSD: Xews4800mips.man,v 1.1 2005/12/29 15:43:40 tsutsui Exp $
.\"
.Dd Dec 30, 2005
.Dt Xews4800mips 1
.Os NetBSD
.Sh NAME
.Nm Xews4800mips
.Nd X Window System Display Server for NetBSD/ews4800mips
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Sh DESCRIPTION
.Nm
is the server for Version 11 of the X Window System for 
.Nx Ns /ews4800mips .
It will normally be started by the
.Xr xdm 1
daemon or by a script that runs the program
.Xr xinit 1 .
.Sh SUPPORTED HARDWARE
.Nm
supports the builtin graphics controller on ews4800mips console,
and it can be used as 8-bit color server.
.Pp
.Nm
supports the builtin keyboard and the builtin mouse for input devices. 
.Sh OPTIONS
In addition to the normal server options described in the
.Xr Xserver 1
manual page.
.Sh SEE ALSO
.Xr X 1 ,
.Xr Xserver 1 ,
.Xr xdm 1 ,
.Xr xinit 1 ,
.Xr xkbcomp 1 ,
.Xr xmodmap 1
.Sh HISTORY
.Nm
was based on Xhpc server for
.Nx Ns /hpcmips ,
which was originally written by TAKEMURA Shin
.Aq takemura@NetBSD.org ,
and Xdreamcast which was ported by Yasushi Oshima
.Aq oshimaya@sc.starcat.ne.jp .
.Sh BUGS
.Nm
is still experimental, and there is no hardware acceleration support yet.
