.\" $XFree86: xc/programs/Xserver/hw/tinyx/fbdev/Xfbdev.man,v 1.2 2005/03/12 23:36:27 dawes Exp $
.\"
.TH Xfbdev 1 __vendorversion__
.SH NAME
Xfbdev \- Linux framebuffer device tiny X server
.SH SYNOPSIS
.B Xfbdev
.RI [ :display ] 
.RI [ option ...]
.SH DESCRIPTION
.B Xfbdev
is a generic X server for Linux.
.B Xfbdev
doesn't know about any particular hardware, and uses the framebuffer
provided by the Linux framebuffer device.
.SH OPTIONS
.B Xfbdev
accepts the common options of the TinyX family of servers.  Please
see TinyX(1).
.SH SEE ALSO
X(__miscmansuffix__), Xserver(1), TinyX(1), xdm(1), xinit(1), XFree86(1).
.SH AUTHORS
The
.B Xfbdev
server was written by Keith Packard.

