#	$NetBSD: Makefile,v 1.7 1999/09/14 08:21:45 fredb Exp $
#
# build and install xsrc

all: all-xc all-contrib

all-xc:
.if exists(xc/xmakefile) && defined(UPDATE)
	@cd xc && ${MAKE} Everything
.else
	@-rm -f xc/xmakefile
	@cd xc && ${MAKE} World
.endif

all-contrib:
.if !exists(contrib/Makefile)
	@cd contrib && PATH=../xc/config/imake:$$PATH \
	    sh ../xc/config/util/xmkmf -a ../xc ../contrib
.endif
	@cd contrib && ${MAKE}

install: install-xc install-contrib

install-xc:
	@cd xc && ${MAKE} install && ${MAKE} install.man

install-contrib:
	@cd contrib && ${MAKE} install && ${MAKE} install.man

clean:
	@-cd xc && ${MAKE} clean
	@-cd contrib && ${MAKE} clean

cleandir distclean: clean
	find xc contrib -name .depend | xargs rm
	find xc contrib -name 'Makefile*' | \
	xargs grep -l "Makefile generated by imake" | xargs rm
	-rmdir xc/exports
	rm -f xc/xmakefile

build:
.if defined(UPDATE)
	@${MAKE} all install
.else
	@${MAKE} cleandir all install
.endif
