.\"	$NetBSD: xsetwallpaper.1,v 1.2 2022/02/11 14:43:01 wiz Exp $
.\"
.\" Copyright (c) 2022 Jared D. McNeill <jmcneill@invisible.ca>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd February 11, 2022
.Dt XSETWALLPAPER 1
.Os
.Sh NAME
.Nm xsetwallpaper
.Nd draw an image on the root window
.Sh SYNOPSIS
.Nm
.Op Fl s
.Op Fl f Ar color
.Ar file
.Sh DESCRIPTION
The
.Nm
draws an image on the root window.
The image is centered and any remaining space is filled with a solid color.
Alternatively the image can be scaled instead.
.Pp
The following options are available:
.Bl -tag -width Fl
.It Fl f Ar color
The fill color for any margins if the image is centered.
The default fill color is black.
.It Fl s
Scale the image instead of centering it.
.El
.Pp
Image formats are those supported by the STB image library.
See
.Lk http://nothings.org/stb
.Sh SEE ALSO
.Xr xsetroot 1
.Sh HISTORY
.Nm
utility appeared in
.Nx 6.0 .
.Sh AUTHORS
.An Jared D. McNeill Aq Mt jmcneill@invisible.ca
