.\"	$NetBSD: Xdreamcast.man,v 1.1 2004/02/07 02:39:07 rtr Exp $
.\"
.Dd Dec 23, 2003
.Dt Xdreamcast 1
.Os NetBSD
.Sh NAME
.Nm Xdreamcast
.Nd X Window System Display Server for NetBSD/dreamcast
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Sh DESCRIPTION
.Nm
is the server for Version 11 of the X Window System for 
.Nx Ns /dreamcast .
It will normally be started by the
.Xr xdm 1
daemon or by a script that runs the program
.Xr xinit 1 .
.Sh SUPPORTED HARDWARE
.Nm
supports the builtin PowerVR2 graphics controller on Dreamcast console,
and it can be used as 16-bit color server.
.Pp
.Nm
supports the Maple keyboards (including Japanese, European, and US keymaps)
and the Maple mice for input devices. 
.Sh OPTIONS
In addition to the normal server options described in the
.Xr Xserver 1
manual page.
.Sh SEE ALSO
.Xr X 1 ,
.Xr Xserver 1 ,
.Xr xdm 1 ,
.Xr xinit 1 ,
.Xr xkbcomp 1 ,
.Xr xmodmap 1
.Sh HISTORY
.Nm
was based on Xhpc server for
.Nx Ns /hpcmips ,
which was originally written by TAKEMURA Shin
.Aq takemura@NetBSD.org ,
and was ported by Yasushi Oshima
.Aq oshimaya@sc.starcat.ne.jp .
.Sh BUGS
.Nm
is still experimental, and there is no hardware acceleration support yet.
