#! /bin/sh
# $XConsortium: xmseconfig /main/1 1996/09/21 14:14:44 kaleb $
#
#
#
#
# $XFree86: xc/programs/Xserver/hw/xfree86/XF86Setup/scripts/xmseconfig,v 3.1 1996/08/20 13:09:33 dawes Exp $
#

exec XF86Setup -script mseconfig.tcl "$@"
