# $XFree86: xc/programs/Xserver/hw/xfree86/XF86Setup/texts/ja/messages.tcl,v 1.1.2.6 1999/04/26 07:23:33 hohndel Exp $
#
# messages in done.tcl :
set messages(done.1)	"\n\
	設定をすべて完了してよろしいですか？\n\n\
	よければ <完了> ボタンを押すことで、この設定で X サーバーを\n\
	立ちあげることができます。\n\
	まだ設定を続けたい場合は画面上にあるボタンを押して設定を続け、\n\
	設定が終ったら最後にもう一度 <設定終了> ボタンを押して下さい。"
set messages(done.2) "完了"

# messages in srvflags :
set messages(srvflags.1) "サーバー設定のオプション\n\n\
	これらのオプションはあらかじめ、通常の設定が選択されています。\n\
	おそらく、変更の必要はないでしょう。"
set messages(srvflags.2) "Ctrl-Alt-Backspace の三つのキーを押すことで\n\
	サーバーを強制終了できるようにする。"
set messages(srvflags.3) "サーバーが立ち上がった状態での解像度変更を\n\
	できるようにする。 "
set messages(srvflags.4) "シグナルを無視する … \n\
	　　　　　 prevents the server from exitting cleanly"
set messages(srvflags.5) "他のホストによって解像度を変更できるようにする"
set messages(srvflags.6) "他のホストによってキーボードとマウスの\n\
	設定を変更できるようにする"

# messages in phase2 :
set messages(phase2.1) "立ちあげています。しばらくお待ち下さい。\n\n\n"
set messages(phase2.2) \
	"サーバーからキーボード情報を読み込むことができませんでした。\n\n\
	XKEYBOARD extension を組み込んでいないか、無効に \
	しているサーバーを使用していませんか？\n\n\
	XKEYBOARD extension は不可欠ではありませんが、ない場合に \
	キーボード設定が十分にできないおそれがあります。\n\n\
	続行します…"
set messages(phase2.3) マウス(M)
set messages(phase2.4) キーボード(K)
set messages(phase2.5) カード(C)
set messages(phase2.6) ディスプレイ(D)
set messages(phase2.7) 解像度(M)
set messages(phase2.8) その他(O)
set messages(phase2.9) 中止(A)
set messages(phase2.10) 設定終了(D)
set messages(phase2.11) ヘルプ(H)
if !$pc98 {
    set messages(phase2.12) "\n\
まず、このメッセージやヘルプの下の方が読めない場合、PageUp/Downなどのキーを\n\
押すことでスクロールすることができます。\n\n\
サーバーの設定は、6つの部分にわかれています。\n\
\tマウス\t\t… マウスのプロトコル、通信速度などを設定します。\n\
\tキーボード\t\t… キーボードの言語とレイアウトを設定します。\n\
\tカード\t\t… 使用するグラフィック・アクセラレータ(SVGA カード) \n\
\t\t\t の設定を行ないます。\n\
\tディスプレイ\t… ディスプレイが表示できる水平・垂直周波数を\n\
\t\t\t 設定します。\n\
\t解像度\t\t… 画面の解像度と色数を設定します。\n\
\tその他\t\t… その他の設定を行ないます。\n\n\
まず、マウスの設定から始めることをお勧めします。(Enter キーを押せば\n\
設定が始まります。)\n\
すべての設定が終ったら、下にある<設定終了> のボタンを押して下さい。\n\n\
ボタンを選ぶ時は、CTRL または ALT キーと下線が引いてある文字（たとえば、\n\
マウスなら CTRL+'M' キー）を押す、カーソルキーやTAB キーでその選択肢に\n\
カーソルを合わせて ENTER を押す、マウスでボタンを左クリックする、などを\n\
して下さい。また、'?'キーを押すか、HELP ボタンをクリックすれば各設定に\n\
ついて、ヘルプを見ることができます。"
} else {
    set messages(phase2.12) "\n\
まず、このメッセージやヘルプの下の方が読めない場合、ROLLUP/DOWNなどのキーを\n\
押すことでスクロールすることができます。\n\n\
サーバーの設定は、5つの部分にわかれています。\n\
\tマウス\t\t… マウスのプロトコル、通信速度などを設定します。\n\
\tカード\t\t… 使用するグラフィック・アクセラレータ(SVGA カード) \n\
\t\t\t の設定を行ないます。\n\
\tディスプレイ\t… ディスプレイが表示できる水平・垂直周波数を\n\
\t\t\t 設定します。\n\
\t解像度\t\t… 画面の解像度と色数を設定します。\n\
\tその他\t\t… その他の設定を行ないます。\n\n\
まず、マウスの設定から始めることをお勧めします。\n\
\t（リターンキーを押せば設定が始まります。）\n\
すべての設定が終ったら、下にある<設定終了> のボタンを押して下さい。\n\n\
ボタンを選ぶ時は、CTRL または GRPH キーと下線が引いてある文字(たとえば、\n\
マウスなら CTRL+'M' キー）を押す、カーソルキーや TAB キーでその選択肢に\n\
カーソルを合わせて リターンキーを押す、マウスでボタンを左クリックする、\n\
などをして下さい。また、'?'キーを押すか、HELP ボタンをクリックすれば\n\
各設定について、ヘルプを見ることができます。"
}
set messages(phase2.13) "ヘルプ終了"
# messages in phase4 :
set messages(phase4.1) "立ちあげています。しばらくお待ち下さい。"
# phase.2-5 is generated by proc 'make_message_phase4'.
set messages(phase4.6) "Okey"
set messages(phase4.7) \
	"画面の大きさやディスプレイ上での画面の位置など、画面の設定を\n\
	変更するために xvidtune を使用することができます。\n\
	変更の必要がないなら終了して下さい。\n\n\n\
	設定を保存するとき、すでに他の設定が存在していればバックアップ\n\
	として保存されます。"
set messages(phase4.8) "設定を保存するファイル名"
set messages(phase4.9) "xvidtune を使用する"
set messages(phase4.10) "設定をファイルに保存して、終了する"
set messages(phase4.11) "中断 … 設定を保存しないで終了する"
set messages(phase4.12) "設定を中断しました。"
set messages(phase4.13) "おめでとうございます、\
	サーバーの設定が完了しました\n\n"

# messages in card.tcl :
set messages(card.1) "選択されたグラフィックカード :"
set messages(card.2) "グラフィックカードは選択されていません。"
set messages(card.3) "README ファイルを読む"
set messages(card.4) "詳細設定"
set messages(card.5) サーバー:
set messages(card.7) チップセット
set messages(card.8) RamDac
set messages(card.9) クロックチップ
set messages(card.10) "RAMDAC Max Speed"
set messages(card.11) "Probed"
set messages(card.12) "Video RAM"
set messages(card.13) "Probed"
set messages(card.14) "256 キロ"
set messages(card.15) "512 キロ"
set messages(card.16) "1 メガ"
set messages(card.17) "2 メガ"
set messages(card.18) "3 メガ"
set messages(card.19) "4 メガ"
set messages(card.20) "6 メガ"
set messages(card.21) "8 メガ"
set messages(card.22) "選択された\nオプション:"
set messages(card.23) "XF86Config の Device の項に付け加える設定:"
#set messages(card.24) "Probed: Yes"
#set messages(card.25) "Probed: No"
set messages(card.26) "カードの選択"
set messages(card.27) "詳細設定"
set messages(card.28) "選択されたグラフィックカード: "
set messages(card.29) "終了"
set messages(card.30) \
	" まず、サーバーが正しいかどうか確かめてから、必要なら設定を変更して下さい。\n\
	チップセット、RamDac 、クロックチップが空欄の場合、自動認識されます。"
set messages(card.31) \
	" リストから使っているグラフィックカードを選んで下さい。\n\
	もし、使っているカードがリストにない場合、詳細設定の \n\
	ボタンを押して下さい。"
set messages(card.32) \
	"通常の設定でよければ、カードの設定はこれで十分です。\n\
	通常と違う設定をしたい場合、詳細設定のボタンを押して下さい。"
set messages(card.33) \
	"通常の設定でよければ、カードの設定はこれで十分です。\n\
	ただし、確認のために README を読むようにしましょう。\n\
	もし、なんらかの変更が必要であれば詳細設定のボタンを\n\
	押して下さい。"
set messages(card.34) \
	"このカードは、XFree86 ではまだ完全にはサポートされて\n\
	いません。ただし、通常のVGA モードで動くように\n\
	設定は済んでいます。"
set messages(card.35) "12 メガ"
set messages(card.36) "16 メガ"

# messages in keyboard.tcl :
set messages(keyboard.1) "モデル:"
set messages(keyboard.2) "レイアウト (言語):"
set messages(keyboard.3) "設定実行"
set messages(keyboard.4) \
		"正しいモデルとレイアウトを選んで下さい。"
set messages(keyboard.5) "使うことのできるオプション :"
set messages(keyboard.6) \
		"Variant (non U.S. Keyboards only):"
set messages(keyboard.7) "既定値を使用する"
set messages(keyboard.8) "失敗しました。やり直して下さい。"
set messages(keyboard.9) "設定中です…"
set messages(keyboard.10) "お待ち下さい…"

# messages in modeselect.tcl :

set messages(modeselect.1) "利用したい解像度を選択して下さい"
set messages(modeselect.2) 640x480
set messages(modeselect.3) 800x600
set messages(modeselect.4) 1024x768
set messages(modeselect.5) 1152x864
set messages(modeselect.6) 1280x1024
set messages(modeselect.7) 1600x1200
set messages(modeselect.8) 640x400
set messages(modeselect.9) 320x200
set messages(modeselect.10) 320x240
set messages(modeselect.11) 400x300
set messages(modeselect.12) 480x300
set messages(modeselect.13) 512x384
set messages(modeselect.14) "使用する色数を選択して下さい"
set messages(modeselect.15) " 256色 "
set messages(modeselect.16) " 65536色 "
set messages(modeselect.17) " 1600万色(Packed) "
set messages(modeselect.18) " 1600万色 "

# messages in monitor.tcl :

set messages(monitor.1) "ディスプレイの周波数"
set messages(monitor.2) "選択されたディスプレイ:"
set messages(monitor.3) "水平周波数"
set messages(monitor.4) "垂直周波数"
set messages(monitor.5) \
	"ディスプレイに表示可能な水平・垂直周波数を入力して下さい。\n\
	わからなければ、リストから最適と思われるものを選択して下さい。"

# messages in mouse.tcl :

set messages(mouse.1) "Lines/inch"
set messages(mouse.2) "サンプル\nレート"
set messages(mouse.3) "マウスの種類を選んで下さい"
set messages(mouse.4) "設定中…"
set messages(mouse.5) "マウスのあるデバイス"
set messages(mouse.6) "Emulate3Buttons"
set messages(mouse.7) ChordMiddle
set messages(mouse.8) "通信速度"
set messages(mouse.9) "? または CTRL-H を押せば、キーボードの使い方が表示されます。"
set messages(mouse.10) フラグ
set messages(mouse.11) "DTRを\nクリアする"
set messages(mouse.12) "RTSを\nクリアする"
set messages(mouse.13) "サンプル\nレート"
set messages(mouse.14) "3ボタンエミュ\nレートの閾値"
set messages(mouse.15) "設定実行"
set messages(mouse.16) "? または CTRL-H を押せば、キーボードの使い方が表示されます。"
set messages(mouse.17) "終了(X)"
set messages(mouse.18) 3
set messages(mouse.19) "感度"
set messages(mouse.20) "高"
set messages(mouse.21) "中"
set messages(mouse.22) "低"
set messages(mouse.23) "ボタン数"
