LIBRARY Xft
VERSION LIBRARY_VERSION
EXPORTS

_XftMatchSymbolic
XftCharExists
XftCharIndex
XftColorAllocName
XftColorAllocValue
XftColorFree
XftDefaultGetBool
XftDefaultGetDouble
XftDefaultGetInteger
XftDefaultHasRender
XftDefaultParseBool
XftDefaultSet
XftDefaultSubstitute
XftDrawChange
XftDrawCharSpec
XftDrawCreate
XftDrawCreateBitmap
XftDrawDestroy
XftDrawRect
XftDrawSetClip
XftDrawString16
XftDrawString32
XftDrawString8
XftDrawStringUtf8
XftDrawPicture
XftDrawSrcPicture
XftInit
XftInitFtLibrary
XftFontClose
XftFontMatch
XftFontOpen
XftFontOpenName
XftFontOpenPattern
XftFontOpenXlfd
XftListFonts
XftListFontsPatternObjects
XftNameParse
XftNameUnparse
XftTextExtents16
XftTextExtents32
XftTextExtents8
XftTextExtentsUtf8
XftXlfdParse

/* $XFree86: xc/lib/Xft/Xft-def.cpp,v 1.8 2005/02/07 01:38:23 tsi Exp $ */
