.\" $XFree86: xc/programs/Xserver/hw/xfree86/input/eloinput/eloinput.man,v 1.1 2005/01/21 14:03:49 tsi Exp $
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH ELOINPUT __drivermansuffix__ __vendorversion__
.SH NAME
eloinput \- Elographics USB input driver
.SH SYNOPSIS
.B "Section \*qInputDevice\*q"
.br
.BI "  Identifier \*q" idevname \*q
.br
.B  "  Driver \*qeloinput\*q"
.br
.BI "  Option \*qDevice\*q   \*q" devpath \*q
.br
\ \ ...
.br
.B EndSection
.SH DESCRIPTION
.B eloinput 
is an XFree86 input driver for Elographics Touchscreen monitors that
utilize the ELO 2500U USB-based controller, using the Linux Input
API. 
.PP
The
.B eloinput
driver functions as a pointer input device, and may be used as the
X server's core pointer.
.SH SUPPORTED HARDWARE
Touch screen monitor manufactured by Elo Graphics that utilize the
2500U USB touchscreen controller.
.SH CONFIGURATION DETAILS
Please refer to XF86Config(__filemansuffix__) for general configuration
details and for options that can be used with all input drivers.  This
section only covers configuration details specific to this driver.
.PP
Config details...
.SH "SEE ALSO"
XFree86(1), XF86Config(__filemansuffix__), xf86config(1), Xserver(1), X(__miscmansuffix__).
.SH AUTHORS
Authors include...
 Patrick Lecoanet
