#! /bin/sh
# $XConsortium: xmseconfig /main/1 1996/09/21 14:14:44 kaleb $
#
#
#
#
# $XFree86: xc/programs/Xserver/hw/xfree98/XF86Setup/scripts/xmseconfig,v 1.1.2.1 1998/02/15 16:09:44 hohndel Exp $
#

exec XF98Setup -script mseconfig.tcl "$@"
