.\" $NetBSD: Xhpc.man,v 1.6 2009/08/15 03:58:10 uwe Exp $
.\"
.\" Copyright (c) 2000 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Takemura Shinichi.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 25, 2000
.Dt XHPC 1
.Os
.Sh NAME
.Nm Xhpc
.Nd X Window System Display Server for the NetBSD/hpc ports
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is the server for Version 11 of the X Window System on Windows CE hardware
running
.Nx .
It will normally be started by the
.Xr xdm 1
daemon or by a script that runs the program
.Xr xinit 1 .
.Sh SUPPORTED HARDWARE
.Nm
support 8-bit or 24-bit color server.
.Pp
.Nm
supports the compact type keyboards.
The
initial arrangement of the keys on the keyboards is configured
as the typewriter style
.Sq ( ASCII
arrangement).
Once it is started, the arrangement is freely configured with
.Xr xmodmap 1
or
.Xr xkbcomp 1
utility.
.Pp
The pointing device can be the touch panel, or USB mouse.
Touch panel supported on NEC mobile Gear Series.
USB mouse supported
on Sharp Telios.
.Pp
the touch panel can emulate 3-button mouse.
.Bl -tag -width Fl
.It Fl "just touch"
= click left button
.It Fl "[Menu] + touch + 2"
= click middle button
.It Fl "[Menu] + touch + 3"
= click right button
.El
Also, you can use 4th and 5th button.
.\"
.Sh OPTIONS
In addition to the normal server options described in the
.Xr Xserver 1
manual page.
.Sh SEE ALSO
.Xr X 1 ,
.Xr Xserver 1 ,
.Xr xdm 1 ,
.Xr xinit 1 ,
.Xr xkbcomp 1 ,
.Xr xmodmap 1
.\"
.Sh HISTORY
.Nm
was originally written by
.An TAKEMURA Shin Aq takemura@NetBSD.org
Officially appeared in
.Nx 1.5 .
3-button emulation code written by Matthew Orgass.
.\"
.Sh BUGS
.Nm
should support Monochrome screen machine.
